### ISSUE TITLE
Replace all /tmp directories with relative temp dir

### ISSUE THREAD

**Issue by jdolitsky** [helm/acceptance-testing#31]
Instead of hardcoding /tmp everywhere, we should instead make a temporary directory using mktemp.

Example:

```
TMPDIR="$(mktemp -d -p ${PWD} --suffix=-helm-acceptance)"
trap "rm -rf ${TMPDIR}" EXIT
```

**Comment by marckhouzam** [comment]
Turns out `mktemp` takes different flags on Mac vs Ubuntu vs Alpine...

I'll look for a generic usage that will work everywhere.
