### ISSUE TITLE
Test Helm on different shells

### ISSUE THREAD

**Issue by jdolitsky** [helm/acceptance-testing#8]
Test Helm features across shells (bash 4, bash 3, zsh, etc.)

Related to https://github.com/helm/helm/pull/6120 cc @marckhouzam

**Comment by marckhouzam** [comment]
Do you mean "Test Helm shell completion across different shells..." or did you have something larger in mind?

I think the shell matters greatly for completion but I don't believe it will affect other features.

**Comment by jdolitsky** [comment]
@marckhouzam I think we should just add a `shells.robot` (or something similar), with the first test case inside being `Verify command completion works`. This opens up the possibility of adding other shell-specifc tests in the future.

Please see [kubernetes_versions.robot#L45](https://github.com/helm/acceptance-testing/blob/master/kubernetes_versions.robot#L45) for an example (similar to `Verify --wait flag works as expected` test case)

**Comment by marckhouzam** [comment]
@jdolitsky Sounds good.  I'll give it a try.

**Comment by marckhouzam** [comment]
@jdolitsky The way things are currently setup, when I add a `shells.robot` file, then whenever I want to run the shell-completion tests, it will run the entire acceptance test-suite, which is already long (over 7 min on my machine).  So to test completion during development, this becomes difficult.

Would it be ok to split things so I could do `make shells` which will only run `shells.robot`?
And `make acceptance` can run both `shells.robot` and `kubernetes_versions.robot`?

**Comment by jdolitsky** [comment]
@marckhouzam It would be my preference/suggestion that instead of adding a separate make target, we find the appropriate way to do this with robot. Then we can maybe have an option `ROBOT_RUN_TESTS` that defaults to all tests ( `ROBOT_RUN_TESTS=kubernetes_versions,shells`).

This way you could do something like
```
ROBOT_RUN_TESTS=shells
make acceptance
```

**Comment by marckhouzam** [comment]
@jdolitsky  Good idea. And it turns out to be much easier than adding a new target.

**Comment by marckhouzam** [comment]
Proposed implementation of `ROBOT_RUN_TESTS` in #10

**Comment by jdolitsky** [comment]
closed via #12
